---

version: '3'

services:
  aliyun-ddns:
    image: symbolspace/aliyun-ddns
    container_name: aliyun-ddns
    hostname: aliyun-ddns
    restart: always
    # outbound requests only
    network_mode: "host"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./../data/aliyun.ddns.config.json:/app/aliyun.ddns.config.json
